# Generated by Django 5.2.8 on 2026-01-10 10:14

import django.db.models.deletion
import uuid
import wama_lab.face_analyzer.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('realtime', 'Real-time (Webcam)'), ('video', 'Video File')], default='video', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('input_file', models.FileField(blank=True, null=True, upload_to=wama_lab.face_analyzer.models.analysis_upload_path)),
                ('output_file', models.FileField(blank=True, null=True, upload_to=wama_lab.face_analyzer.models.result_upload_path)),
                ('config', models.JSONField(default=dict)),
                ('results_summary', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('progress', models.FloatField(default=0.0)),
                ('error_message', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_analysis_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Analysis Session',
                'verbose_name_plural': 'Analysis Sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_number', models.IntegerField()),
                ('timestamp', models.FloatField()),
                ('face_detected', models.BooleanField(default=False)),
                ('head_pose', models.JSONField(blank=True, null=True)),
                ('rppg_data', models.JSONField(blank=True, null=True)),
                ('eye_tracking_data', models.JSONField(blank=True, null=True)),
                ('emotion_data', models.JSONField(blank=True, null=True)),
                ('respiration_data', models.JSONField(blank=True, null=True)),
                ('processing_time_ms', models.FloatField(default=0.0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frames', to='face_analyzer.analysissession')),
            ],
            options={
                'ordering': ['session', 'frame_number'],
                'unique_together': {('session', 'frame_number')},
            },
        ),
    ]
