# Generated by Django 5.2.8 on 2026-03-18 10:57

import django.core.validators
import wama.common.utils.media_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('describer', '0005_description_coherence_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='source_url',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='description',
            name='input_file',
            field=models.FileField(blank=True, upload_to=wama.common.utils.media_paths.UploadToUserPath('describer', 'input'), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp', 'bmp', 'mp4', 'avi', 'mov', 'mkv', 'webm', 'mp3', 'wav', 'flac', 'ogg', 'm4a', 'txt', 'pdf', 'docx', 'md', 'csv'])]),
        ),
    ]
